version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api/:/usr/app"
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend : null



